### ISSUE TITLE
ToDo-List

### ISSUE THREAD

**Issue by zapp-brannigan** [zapp-brannigan/LibVirtKvm-scripts#1]
- [x] Rotate backups of not runnings domains if the file has changed since the last backup

- [x] Move functions outside the main script and source them

- [x] Option to delete old backupsets

- [x] Option to use systemd journal as log-destination

- [x] Improve logging during backup

- [x] Use a config file

- [x] Restore script/helper

- [x] Skip backups of blockdevices which are already backed up

- [x] Remove newlines in "(NOT) RUNNING to backup"

- [x] Allow more then one domain to backup without using "all"

- [x] Restore as "new" domain, don't requiere the "old" domain to be undefined

- [x] Do not fail the backup if "quiescencing" isn't possible. Do a "normal" backup instead.

- [x] Rotate backups if the domain is offline and the last backup was online (and vice versa)

- [ ] Explain options in the config file

- [x] Show long options in usage

- [x] Remove "snapshot=" from config file

- [ ] Dump state is not working anymore (???); have to investigate that
